activity_data = [
    {"city": "Pretoria", "name": "Union Buildings Tour", "type": "Culture", "cost": 0.0, "rating": 4.7},
    {"city": "Pretoria", "name": "National Zoological Gardens", "type": "Family", "cost": 10.0, "rating": 4.5},
    {"city": "Pretoria", "name": "Freedom Park Visit", "type": "Historical", "cost": 5.0, "rating": 4.6},
    {"city": "Pretoria", "name": "Loftus Versfeld Stadium Tour", "type": "Adventure", "cost": 8.0, "rating": 4.4},
    {"city": "Pretoria", "name": "Groenkloof Nature Reserve", "type": "Nature", "cost": 6.0, "rating": 4.8},
    {"city": "Amsterdam", "name": "Van Gogh Museum", "type": "Culture", "cost": 25.0, "rating": 4.8},
    {"city": "Amsterdam", "name": "Canal Cruise", "type": "Relaxation", "cost": 20.0, "rating": 4.5},
    {"city": "Amsterdam", "name": "Anne Frank House", "type": "Culture", "cost": 15.0, "rating": 4.7},
    {"city": "Amsterdam", "name": "Vondelpark Picnic", "type": "Relaxation", "cost": 0.0, "rating": 4.6},
    {"city": "Paris", "name": "Eiffel Tower Visit", "type": "Adventure", "cost": 30.0, "rating": 4.7},
    {"city": "Paris", "name": "Louvre Museum", "type": "Culture", "cost": 17.0, "rating": 4.9},
    {"city": "Paris", "name": "Seine River Cruise", "type": "Relaxation", "cost": 25.0, "rating": 4.6},
    {"city": "Paris", "name": "Montmartre Walk", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Rome", "name": "Colosseum Tour", "type": "Culture", "cost": 20.0, "rating": 4.9},
    {"city": "Rome", "name": "Vatican Museums", "type": "Culture", "cost": 25.0, "rating": 4.8},
    {"city": "Rome", "name": "Trevi Fountain Visit", "type": "Relaxation", "cost": 0.0, "rating": 4.7},
    {"city": "Rome", "name": "Pantheon Walk", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Barcelona", "name": "Sagrada Familia", "type": "Culture", "cost": 26.0, "rating": 4.8},
    {"city": "Barcelona", "name": "Park Güell", "type": "Relaxation", "cost": 10.0, "rating": 4.7},
    {"city": "Barcelona", "name": "Gothic Quarter Tour", "type": "Culture", "cost": 15.0, "rating": 4.6},
    {"city": "Barcelona", "name": "Magic Fountain Show", "type": "Relaxation", "cost": 0.0, "rating": 4.5},
    {"city": "Berlin", "name": "Brandenburg Gate", "type": "Culture", "cost": 0.0, "rating": 4.7},
    {"city": "Berlin", "name": "Berlin Wall Memorial", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Berlin", "name": "Museum Island", "type": "Culture", "cost": 12.0, "rating": 4.7},
    {"city": "Berlin", "name": "Checkpoint Charlie", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Lisbon", "name": "Belém Tower", "type": "Adventure", "cost": 10.0, "rating": 4.6},
    {"city": "Lisbon", "name": "Alfama District Walk", "type": "Culture", "cost": 0.0, "rating": 4.7},
    {"city": "Lisbon", "name": "Tram 28 Ride", "type": "Relaxation", "cost": 3.0, "rating": 4.5},
    {"city": "Lisbon", "name": "Jerónimos Monastery", "type": "Culture", "cost": 12.0, "rating": 4.6},
    {"city": "Vienna", "name": "Schönbrunn Palace", "type": "Culture", "cost": 22.0, "rating": 4.8},
    {"city": "Vienna", "name": "St. Stephen’s Cathedral", "type": "Culture", "cost": 0.0, "rating": 4.7},
    {"city": "Vienna", "name": "Belvedere Museum", "type": "Culture", "cost": 18.0, "rating": 4.6},
    {"city": "Vienna", "name": "Vienna Opera House", "type": "Culture", "cost": 25.0, "rating": 4.5},
    {"city": "Prague", "name": "Charles Bridge", "type": "Relaxation", "cost": 0.0, "rating": 4.7},
    {"city": "Prague", "name": "Prague Castle", "type": "Culture", "cost": 15.0, "rating": 4.8},
    {"city": "Prague", "name": "Old Town Square", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Prague", "name": "Astronomical Clock", "type": "Culture", "cost": 5.0, "rating": 4.5},
    {"city": "Athens", "name": "Acropolis", "type": "Adventure", "cost": 20.0, "rating": 4.8},
    {"city": "Athens", "name": "Plaka District", "type": "Culture", "cost": 0.0, "rating": 4.7},
    {"city": "Athens", "name": "Temple of Olympian Zeus", "type": "Culture", "cost": 10.0, "rating": 4.6},
    {"city": "Athens", "name": "National Archaeological Museum", "type": "Culture", "cost": 15.0, "rating": 4.5},
    {"city": "Budapest", "name": "Buda Castle", "type": "Culture", "cost": 12.0, "rating": 4.7},
    {"city": "Budapest", "name": "Thermal Baths", "type": "Relaxation", "cost": 18.0, "rating": 4.8},
    {"city": "Budapest", "name": "Parliament Building", "type": "Culture", "cost": 10.0, "rating": 4.6},
    {"city": "Budapest", "name": "Fisherman’s Bastion", "type": "Culture", "cost": 0.0, "rating": 4.5},
    # 60 more entries to reach 100 - repeat the pattern with slight variations:
    {"city": "Amsterdam", "name": "Heineken Experience", "type": "Culture", "cost": 18.0, "rating": 4.4},
    {"city": "Amsterdam", "name": "NEMO Science Museum", "type": "Culture", "cost": 15.0, "rating": 4.3},
    {"city": "Paris", "name": "Notre-Dame Cathedral", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Paris", "name": "Champs-Élysées Walk", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Rome", "name": "Spanish Steps", "type": "Culture", "cost": 0.0, "rating": 4.4},
    {"city": "Rome", "name": "Piazza Navona", "type": "Relaxation", "cost": 0.0, "rating": 4.3},
    {"city": "Barcelona", "name": "Picasso Museum", "type": "Culture", "cost": 15.0, "rating": 4.5},
    {"city": "Barcelona", "name": "Barceloneta Beach", "type": "Relaxation", "cost": 0.0, "rating": 4.6},
    {"city": "Berlin", "name": "Tiergarten Park", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Berlin", "name": "East Side Gallery", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Lisbon", "name": "LX Factory", "type": "Culture", "cost": 0.0, "rating": 4.4},
    {"city": "Lisbon", "name": "Oceanário de Lisboa", "type": "Culture", "cost": 15.0, "rating": 4.3},
    {"city": "Vienna", "name": "Prater Park", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Vienna", "name": "Hundertwasserhaus", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Prague", "name": "Wenceslas Square", "type": "Culture", "cost": 0.0, "rating": 4.3},
    {"city": "Prague", "name": "Petrin Hill", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Athens", "name": "Mount Lycabettus", "type": "Adventure", "cost": 0.0, "rating": 4.5},
    {"city": "Athens", "name": "National Garden", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Budapest", "name": "Great Market Hall", "type": "Foodie", "cost": 0.0, "rating": 4.7},
    {"city": "Budapest", "name": "Gellért Hill", "type": "Adventure", "cost": 0.0, "rating": 4.5},
    {"city": "Amsterdam", "name": "Red Light District Walk", "type": "Adventure", "cost": 0.0, "rating": 4.1},
    {"city": "Paris", "name": "Versailles Day Trip", "type": "Adventure", "cost": 50.0, "rating": 4.8},
    {"city": "Rome", "name": "Trastevere Neighborhood", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Barcelona", "name": "Camp Nou Tour", "type": "Culture", "cost": 25.0, "rating": 4.5},
    {"city": "Berlin", "name": "Berlin Zoo", "type": "Family", "cost": 18.0, "rating": 4.6},
    {"city": "Lisbon", "name": "Santa Justa Lift", "type": "Culture", "cost": 5.0, "rating": 4.4},
    {"city": "Vienna", "name": "Naschmarkt", "type": "Foodie", "cost": 0.0, "rating": 4.7},
    {"city": "Prague", "name": "Boat Ride on Vltava River", "type": "Relaxation", "cost": 15.0, "rating": 4.5},
    {"city": "Athens", "name": "Ancient Agora", "type": "Culture", "cost": 12.0, "rating": 4.6},
    {"city": "Budapest", "name": "House of Terror Museum", "type": "Culture", "cost": 10.0, "rating": 4.6},
    {"city": "Amsterdam", "name": "Flower Market", "type": "Relaxation", "cost": 0.0, "rating": 4.5},
    {"city": "Paris", "name": "Sacré-Cœur", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Rome", "name": "Borghese Gallery", "type": "Culture", "cost": 20.0, "rating": 4.7},
    {"city": "Barcelona", "name": "La Boqueria Market", "type": "Foodie", "cost": 0.0, "rating": 4.8},
    {"city": "Berlin", "name": "Holocaust Memorial", "type": "Culture", "cost": 0.0, "rating": 4.6},
    {"city": "Lisbon", "name": "Fado Music Night", "type": "Culture", "cost": 15.0, "rating": 4.4},
    {"city": "Vienna", "name": "Vienna Zoo", "type": "Family", "cost": 20.0, "rating": 4.5},
    {"city": "Prague", "name": "Strahov Monastery", "type": "Culture", "cost": 8.0, "rating": 4.5},
    {"city": "Athens", "name": "Byzantine and Christian Museum", "type": "Culture", "cost": 10.0, "rating": 4.4},
    {"city": "Budapest", "name": "Danube River Cruise", "type": "Relaxation", "cost": 20.0, "rating": 4.7},
    {"city": "Amsterdam", "name": "Museumplein", "type": "Culture", "cost": 0.0, "rating": 4.5},
    {"city": "Paris", "name": "Luxembourg Gardens", "type": "Relaxation", "cost": 0.0, "rating": 4.6},
    {"city": "Rome", "name": "Ponte Milvio", "type": "Relaxation", "cost": 0.0, "rating": 4.4},
    {"city": "Barcelona", "name": "Palau de la Música Catalana", "type": "Culture", "cost": 20.0, "rating": 4.7},
    {"city": "Berlin", "name": "Museum of Natural History", "type": "Culture", "cost": 12.0, "rating": 4.6},
    {"city": "Lisbon", "name": "MAAT Museum", "type": "Culture", "cost": 10.0, "rating": 4.3},
    {"city": "Vienna", "name": "Museum of Art History", "type": "Culture", "cost": 15.0, "rating": 4.7},
    {"city": "Prague", "name": "Dancing House", "type": "Culture", "cost": 0.0, "rating": 4.4},
    {"city": "Athens", "name": "Philopappos Hill", "type": "Adventure", "cost": 0.0, "rating": 4.5},
    {"city": "Budapest", "name": "Margaret Island", "type": "Relaxation", "cost": 0.0, "rating": 4.6},
]
